###/user/{UserId}
GET http://localhost:9999/user/1

###

POST http://localhost:9999/user
Content-Type: application/json

{
  "id": "testId2123122",
  "password": "testPass",
  "email": "testEmail",
  "name": "testName"
}


### /user/{UserId}
PUT http://localhost:9999/user/1
Content-Type: application/json

{
  "email": "modifyEmail",
  "password": "modifyPass",
  "name": "modifyName"
}

### /user/{UserId}
DELETE http://localhost:9999/user/testId3asdasd3